---
title: "Group 17 CA pollution burden"
author: "Erin de Leon Sanchez and Alissa Patterson"
date: "11/12/2021"
output: html_document
---

```{r setup, include = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)
```

```{r}
# Erin is coding here
ces <- read_csv(here("data", "ces3demographics.csv")) %>% 
  clean_names()
```

```{r}
# Alissa is coding here
ggplot(data = ces, aes(x = white_percent, y = ces_3_0_score)) + 
  geom_point()

```


```{r}
# Erin is coding here
ggplot(data = ces, aes(x = white_percent, y = ces_3_0_score)) + 
  geom_hex() +
  labs(x = "Percent of white people", y = "CalEnviroScreen pollution burden score", caption = "Data from the California Environmental Justice Alliance" ) +
  # Alissa Coding here
  scale_fill_gradient(low = "orange", high = "green") +
   theme(plot.caption = element_text(hjust = 0, size = 12))
```

Figure 1: Percentage of white people versus the CalEnviroScreen (CES) 3.0 score. CES 3.0 scores account for pollution burden and population characteristics. 

Overall, Figure 1 shows that white people live in areas with lower pollution burden scores than people of color.

Data citation: California Office of Environmental Health Hazard Assesment. CalEnviroScreen 3.0. (2018). https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-30 
